from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import routers
from warships.views import PlayerViewSet, ClanViewSet, ShipViewSet
from warships.views import tier_data, activity_data, type_data, randoms_data, ranked_data, clan_members, clan_data, clan_battle_seasons, player_clan_battle_seasons, landing_activity_attrition, landing_best_warmup, landing_clans, landing_recent_clans, landing_players, landing_recent_players, player_name_suggestions, player_summary, players_explorer, wr_distribution, player_distribution, player_correlation_distribution, db_stats, agentic_trace_dashboard, analytics_entity_view, analytics_top_entities
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'player', PlayerViewSet, basename='player')
router.register(r'clan', ClanViewSet, basename='clan')
router.register(r'ship', ShipViewSet, basename='ship')

player_detail_view = PlayerViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy',
})
clan_detail_view = ClanViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy',
})

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^api/player/(?P<pk>[^/]+)$',
            player_detail_view, name='player_detail_no_slash'),
    re_path(r'^api/clan/(?P<clan_id>[^/]+)$',
            clan_detail_view, name='clan_detail_no_slash'),
    path('api/', include(router.urls)),  # Include the router URLs
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/fetch/tier_data/<str:player_id>/',
         tier_data, name='fetch_tier_data'),
    path('api/fetch/tier_data/<str:player_id>',
         tier_data, name='fetch_tier_data_no_slash'),
    path('api/fetch/activity_data/<str:player_id>/',
         activity_data, name='fetch_activity_data'),
    path('api/fetch/activity_data/<str:player_id>',
         activity_data, name='fetch_activity_data_no_slash'),
    path('api/fetch/type_data/<str:player_id>/',
         type_data, name='fetch_type_data'),
    path('api/fetch/type_data/<str:player_id>',
         type_data, name='fetch_type_data_no_slash'),
    path('api/fetch/randoms_data/<str:player_id>/',
         randoms_data, name='fetch_randoms_data'),
    path('api/fetch/randoms_data/<str:player_id>',
         randoms_data, name='fetch_randoms_data_no_slash'),
    path('api/fetch/ranked_data/<str:player_id>/',
         ranked_data, name='fetch_ranked_data'),
    path('api/fetch/ranked_data/<str:player_id>',
         ranked_data, name='fetch_ranked_data_no_slash'),
    path('api/fetch/player_summary/<str:player_id>/',
         player_summary, name='fetch_player_summary'),
    path('api/fetch/player_summary/<str:player_id>',
         player_summary, name='fetch_player_summary_no_slash'),
    path('api/fetch/clan_members/<str:clan_id>/',
         clan_members, name='fetch_clan_members'),
    path('api/fetch/clan_members/<str:clan_id>',
         clan_members, name='fetch_clan_members_no_slash'),
    path('api/fetch/clan_data/<str:clan_filter>',
         clan_data, name='fetch_clan_data'),
    path('api/fetch/clan_battle_seasons/<str:clan_id>/',
         clan_battle_seasons, name='fetch_clan_battle_seasons'),
    path('api/fetch/clan_battle_seasons/<str:clan_id>',
         clan_battle_seasons, name='fetch_clan_battle_seasons_no_slash'),
    path('api/fetch/player_clan_battle_seasons/<str:player_id>/',
         player_clan_battle_seasons, name='fetch_player_clan_battle_seasons'),
    path('api/fetch/player_clan_battle_seasons/<str:player_id>',
         player_clan_battle_seasons, name='fetch_player_clan_battle_seasons_no_slash'),
    path('api/landing/activity-attrition/',
         landing_activity_attrition, name='landing_activity_attrition'),
    path('api/landing/activity-attrition',
         landing_activity_attrition, name='landing_activity_attrition_no_slash'),
    path('api/landing/clans/',
         landing_clans, name='landing_clans'),
    path('api/landing/clans',
         landing_clans, name='landing_clans_no_slash'),
    path('api/landing/recent-clans/',
         landing_recent_clans, name='landing_recent_clans'),
    path('api/landing/recent-clans',
         landing_recent_clans, name='landing_recent_clans_no_slash'),
    path('api/landing/players/',
         landing_players, name='landing_players'),
    path('api/landing/players',
         landing_players, name='landing_players_no_slash'),
    path('api/landing/warm-best/',
         landing_best_warmup, name='landing_best_warmup'),
    path('api/landing/warm-best',
         landing_best_warmup, name='landing_best_warmup_no_slash'),
    path('api/landing/player-suggestions/',
         player_name_suggestions, name='player_name_suggestions'),
    path('api/landing/player-suggestions',
         player_name_suggestions, name='player_name_suggestions_no_slash'),
    path('api/landing/recent/',
         landing_recent_players, name='landing_recent_players'),
    path('api/landing/recent',
         landing_recent_players, name='landing_recent_players_no_slash'),
    path('api/players/explorer/',
         players_explorer, name='players_explorer'),
    path('api/players/explorer',
         players_explorer, name='players_explorer_no_slash'),
    path('api/fetch/wr_distribution/',
         wr_distribution, name='fetch_wr_distribution'),
    path('api/fetch/wr_distribution',
         wr_distribution, name='fetch_wr_distribution_no_slash'),
    path('api/fetch/player_distribution/<str:metric>/',
         player_distribution, name='fetch_player_distribution'),
    path('api/fetch/player_distribution/<str:metric>',
         player_distribution, name='fetch_player_distribution_no_slash'),
    path('api/fetch/player_correlation/<str:metric>/<str:player_id>/',
         player_correlation_distribution, name='fetch_player_correlation_distribution_for_player'),
    path('api/fetch/player_correlation/<str:metric>/<str:player_id>',
         player_correlation_distribution, name='fetch_player_correlation_distribution_for_player_no_slash'),
    path('api/fetch/player_correlation/<str:metric>/',
         player_correlation_distribution, name='fetch_player_correlation_distribution'),
    path('api/fetch/player_correlation/<str:metric>',
         player_correlation_distribution, name='fetch_player_correlation_distribution_no_slash'),
    path('api/stats/',
         db_stats, name='db_stats'),
    path('api/stats',
         db_stats, name='db_stats_no_slash'),
    path('api/agentic/traces/',
         agentic_trace_dashboard, name='agentic_trace_dashboard'),
    path('api/agentic/traces',
         agentic_trace_dashboard, name='agentic_trace_dashboard_no_slash'),
    path('api/analytics/entity-view/',
         analytics_entity_view, name='analytics_entity_view'),
    path('api/analytics/entity-view',
         analytics_entity_view, name='analytics_entity_view_no_slash'),
    path('api/analytics/top-entities/',
         analytics_top_entities, name='analytics_top_entities'),
    path('api/analytics/top-entities',
         analytics_top_entities, name='analytics_top_entities_no_slash'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
