services:
  db:
    container_name: battlestats-db
    image: postgres:15
    environment:
      POSTGRES_DB: battlestats
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${DB_PASSWORD:-XVIB58E5rWnAsU6}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: battlestats-redis
    image: "redis:7-alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: battlestats-rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    container_name: battlestats-django
    command: >
      bash -c "python manage.py makemigrations &&
                  python manage.py migrate &&
                  gunicorn --config gunicorn.conf.py battlestats.wsgi:application --bind 0.0.0.0:8888"
    volumes:
      - ./server:/usr/src/app
    env_file:
      - server/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - rabbitmq
      - redis
    ports:
      - "8888:8888" # Expose port 8888 for WSGI server

  react-app:
    build:
      context: client/
      dockerfile: Dockerfile
    container_name: battlestats-react
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
    command: npm run dev -- --port 3001

  task-runner:
    container_name: battlestats-celery
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    command: celery -A battlestats worker -l INFO --time-limit=600 --prefetch-multiplier=1 --max-tasks-per-child=200 --without-gossip --without-mingle
    env_file:
      - server/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - rabbitmq
      - redis

  task-scheduler:
    container_name: battlestats-beat
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    command: celery -A battlestats beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - server/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - task-runner
      - rabbitmq

volumes:
  postgres_data:
