[pytest]
DJANGO_SETTINGS_MODULE = battlestats.settings
filterwarnings =
	ignore:Normally Django will use a connection to the 'postgres' database.*:RuntimeWarning:django\.db\.backends\.postgresql\.base
	ignore:Error when trying to teardown test databases.*:pytest.PytestWarning
