# Generated by Django 5.1.15 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0029_entityvisitdaily_entityvisitevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='actual_kdr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pvp_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pvp_frags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pvp_survived_battles',
            field=models.IntegerField(default=0),
        ),
    ]