# Generated by Django 5.1.15 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0030_player_actual_kdr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerexplorersummary',
            name='clan_battle_overall_win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerexplorersummary',
            name='clan_battle_seasons_participated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerexplorersummary',
            name='clan_battle_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerexplorersummary',
            name='clan_battle_total_battles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]