# Generated by Django 5.1.15 on 2026-03-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0034_drop_unused_indexes_and_optimize'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(unique=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
