# Generated by Django 5.1.15 on 2026-03-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0035_deletedaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedaccount',
            name='account_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
