# Generated by Django 5.2.12 on 2026-03-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0036_deletedaccount_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU')], db_index=True, default='na', max_length=4),
        ),
        migrations.AddField(
            model_name='player',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU')], db_index=True, default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['realm', 'pvp_battles', 'pvp_ratio'], name='player_realm_battles_ratio_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['realm', 'pvp_battles', 'pvp_survival_rate'], name='player_realm_battles_surv_idx'),
        ),
        # Deduplicate any player rows before adding unique constraint
        migrations.RunSQL(
            sql="""
                DELETE FROM warships_player
                WHERE id NOT IN (
                    SELECT MIN(id) FROM warships_player GROUP BY player_id, realm
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Deduplicate any clan rows before adding unique constraint
        migrations.RunSQL(
            sql="""
                DELETE FROM warships_clan
                WHERE id NOT IN (
                    SELECT MIN(id) FROM warships_clan GROUP BY clan_id, realm
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='clan',
            constraint=models.UniqueConstraint(fields=('clan_id', 'realm'), name='unique_clan_per_realm'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('player_id', 'realm'), name='unique_player_per_realm'),
        ),

        # Recreate materialized view with realm column
        migrations.RunSQL(
            sql="""
                DROP MATERIALIZED VIEW IF EXISTS mv_player_distribution_stats;

                CREATE MATERIALIZED VIEW mv_player_distribution_stats AS
                SELECT
                    id,
                    realm,
                    pvp_ratio,
                    pvp_survival_rate,
                    pvp_battles,
                    is_hidden
                FROM warships_player
                WHERE is_hidden = FALSE
                  AND pvp_battles >= 100;

                CREATE UNIQUE INDEX mv_player_dist_id_idx
                    ON mv_player_distribution_stats (id);
                CREATE INDEX mv_player_dist_realm_idx
                    ON mv_player_distribution_stats (realm);
                CREATE INDEX mv_player_dist_ratio_idx
                    ON mv_player_distribution_stats (pvp_ratio)
                    WHERE pvp_ratio IS NOT NULL;
                CREATE INDEX mv_player_dist_survival_idx
                    ON mv_player_distribution_stats (pvp_survival_rate)
                    WHERE pvp_survival_rate IS NOT NULL;
                CREATE INDEX mv_player_dist_battles_idx
                    ON mv_player_distribution_stats (pvp_battles);
                CREATE INDEX mv_player_dist_realm_ratio_idx
                    ON mv_player_distribution_stats (realm, pvp_ratio)
                    WHERE pvp_ratio IS NOT NULL;
                CREATE INDEX mv_player_dist_realm_survival_idx
                    ON mv_player_distribution_stats (realm, pvp_survival_rate)
                    WHERE pvp_survival_rate IS NOT NULL;
            """,
            reverse_sql="""
                DROP MATERIALIZED VIEW IF EXISTS mv_player_distribution_stats;

                CREATE MATERIALIZED VIEW mv_player_distribution_stats AS
                SELECT
                    id,
                    pvp_ratio,
                    pvp_survival_rate,
                    pvp_battles,
                    is_hidden
                FROM warships_player
                WHERE is_hidden = FALSE
                  AND pvp_battles >= 100;

                CREATE UNIQUE INDEX mv_player_dist_id_idx
                    ON mv_player_distribution_stats (id);
                CREATE INDEX mv_player_dist_ratio_idx
                    ON mv_player_distribution_stats (pvp_ratio)
                    WHERE pvp_ratio IS NOT NULL;
                CREATE INDEX mv_player_dist_survival_idx
                    ON mv_player_distribution_stats (pvp_survival_rate)
                    WHERE pvp_survival_rate IS NOT NULL;
                CREATE INDEX mv_player_dist_battles_idx
                    ON mv_player_distribution_stats (pvp_battles);
            """,
        ),
    ]
