# Generated by Django 5.1.15 on 2026-04-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0037_add_realm_to_player_and_clan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entityvisitdaily',
            name='unique_entity_visit_daily',
        ),
        migrations.AddField(
            model_name='entityvisitdaily',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU')], db_index=True, default='na', max_length=4),
        ),
        migrations.AddField(
            model_name='entityvisitevent',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU')], db_index=True, default='na', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='entityvisitdaily',
            constraint=models.UniqueConstraint(fields=('date', 'entity_type', 'entity_id', 'realm'), name='unique_entity_visit_daily_realm'),
        ),
    ]
