# Generated by Django 5.2.12 on 2026-04-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0039_landingplayerbestsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='entityvisitdaily',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='entityvisitevent',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='landingplayerbestsnapshot',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4),
        ),
    ]
