# Generated by Django 5.2.12 on 2026-04-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0040_add_asia_realm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='clan_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='leader_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityvisitdaily',
            name='entity_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='entityvisitevent',
            name='entity_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
