# Generated by Django 5.1.15 on 2026-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0041_widen_ids_to_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_streamer',
            field=models.BooleanField(default=False),
        ),
    ]
