# Generated by Django 5.2.12 on 2026-04-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0043_streamersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitch_handle',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='twitch_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
