# Generated by Django 5.2.12 on 2026-04-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0044_player_twitch_handle_player_twitch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('empty', 'Empty'), ('skipped_hidden', 'Skipped — hidden'), ('skipped_low_battles', 'Skipped — low battles'), ('skipped_inactive', 'Skipped — inactive')], db_index=True, default='pending', max_length=24),
        ),
    ]
