# Generated by Django 5.2.12 on 2026-04-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0046_backfill_enrichment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('empty', 'Empty'), ('skipped_hidden', 'Skipped — hidden'), ('skipped_low_battles', 'Skipped — low battles'), ('skipped_inactive', 'Skipped — inactive'), ('skipped_low_wr', 'Skipped — low win rate')], db_index=True, default='pending', max_length=24),
        ),
    ]
