# Generated by Django 5.2.12 on 2026-04-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0048_clan_name_tag_trgm_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerexplorersummary',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4),
        ),
        migrations.AddIndex(
            model_name='playerexplorersummary',
            index=models.Index(fields=['realm', 'player_score'], name='explorer_realm_score_idx'),
        ),
    ]
