# Generated by Django 5.2.12 on 2026-04-12 03:49

from django.db import migrations


def backfill_realm(apps, schema_editor):
    """Backfill realm from Player to PlayerExplorerSummary using raw SQL for speed."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE warships_playerexplorersummary es
            SET realm = p.realm
            FROM warships_player p
            WHERE es.player_id = p.id
              AND (es.realm IS NULL OR es.realm = 'na')
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0049_add_realm_to_explorer_summary'),
    ]

    operations = [
        migrations.RunPython(backfill_realm, migrations.RunPython.noop),
    ]
