# Generated by Django 5.2.12 on 2026-04-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0050_backfill_explorer_realm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('pvp_battles', models.IntegerField(default=0)),
                ('pvp_wins', models.IntegerField(default=0)),
                ('pvp_losses', models.IntegerField(default=0)),
                ('pvp_frags', models.IntegerField(default=0)),
                ('pvp_survived_battles', models.IntegerField(default=0)),
                ('last_battle_time', models.DateTimeField(blank=True, null=True)),
                ('ships_stats_json', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('poll', 'Poll'), ('manual', 'Manual')], default='poll', max_length=12)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_observations', to='warships.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('ship_id', models.BigIntegerField()),
                ('ship_name', models.CharField(blank=True, default='', max_length=200)),
                ('battles_delta', models.IntegerField(default=0)),
                ('wins_delta', models.IntegerField(default=0)),
                ('losses_delta', models.IntegerField(default=0)),
                ('frags_delta', models.IntegerField(default=0)),
                ('survived', models.BooleanField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_events', to='warships.player')),
                ('from_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_events', to='warships.battleobservation')),
                ('to_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_events', to='warships.battleobservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='battleobservation',
            index=models.Index(fields=['player', '-observed_at'], name='battle_obs_player_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='battleobservation',
            constraint=models.UniqueConstraint(fields=('player', 'observed_at'), name='unique_battle_observation_per_player_time'),
        ),
        migrations.AddIndex(
            model_name='battleevent',
            index=models.Index(fields=['player', '-detected_at'], name='battle_event_player_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='battleevent',
            constraint=models.UniqueConstraint(fields=('from_observation', 'to_observation', 'ship_id'), name='unique_battle_event_per_observation_pair'),
        ),
    ]
