# Generated by Django 5.2.12 on 2026-04-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0051_battle_observation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleevent',
            name='damage_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battleevent',
            name='planes_killed_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battleevent',
            name='xp_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
