# Generated by Django 5.2.12 on 2026-04-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0052_battle_event_combat_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDailyShipStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ship_id', models.BigIntegerField(db_index=True)),
                ('ship_name', models.CharField(blank=True, default='', max_length=200)),
                ('battles', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('frags', models.IntegerField(default=0)),
                ('damage', models.BigIntegerField(default=0)),
                ('xp', models.BigIntegerField(default=0)),
                ('planes_killed', models.IntegerField(default=0)),
                ('survived_battles', models.IntegerField(default=0)),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ship_stats', to='warships.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', '-date'], name='dly_ship_player_date_idx'), models.Index(fields=['player', 'ship_id', '-date'], name='dly_ship_player_shipdt_idx'), models.Index(fields=['date', '-battles'], name='dly_ship_date_battles_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'date', 'ship_id'), name='unique_player_daily_ship_stats')],
            },
        ),
    ]
