# Generated by Django 5.2.12 on 2026-04-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0053_player_daily_ship_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMonthlyShipStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('ship_id', models.BigIntegerField(db_index=True)),
                ('ship_name', models.CharField(blank=True, default='', max_length=200)),
                ('battles', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('frags', models.IntegerField(default=0)),
                ('damage', models.BigIntegerField(default=0)),
                ('xp', models.BigIntegerField(default=0)),
                ('planes_killed', models.IntegerField(default=0)),
                ('survived_battles', models.IntegerField(default=0)),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warships.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', '-period_start'], name='mo_ship_player_period_idx'), models.Index(fields=['player', 'ship_id', '-period_start'], name='mo_ship_player_shipprd_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'period_start', 'ship_id'), name='unique_player_monthly_ship_stats')],
            },
        ),
        migrations.CreateModel(
            name='PlayerWeeklyShipStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('ship_id', models.BigIntegerField(db_index=True)),
                ('ship_name', models.CharField(blank=True, default='', max_length=200)),
                ('battles', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('frags', models.IntegerField(default=0)),
                ('damage', models.BigIntegerField(default=0)),
                ('xp', models.BigIntegerField(default=0)),
                ('planes_killed', models.IntegerField(default=0)),
                ('survived_battles', models.IntegerField(default=0)),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warships.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', '-period_start'], name='wk_ship_player_period_idx'), models.Index(fields=['player', 'ship_id', '-period_start'], name='wk_ship_player_shipprd_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'period_start', 'ship_id'), name='unique_player_weekly_ship_stats')],
            },
        ),
        migrations.CreateModel(
            name='PlayerYearlyShipStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('ship_id', models.BigIntegerField(db_index=True)),
                ('ship_name', models.CharField(blank=True, default='', max_length=200)),
                ('battles', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('frags', models.IntegerField(default=0)),
                ('damage', models.BigIntegerField(default=0)),
                ('xp', models.BigIntegerField(default=0)),
                ('planes_killed', models.IntegerField(default=0)),
                ('survived_battles', models.IntegerField(default=0)),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warships.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', '-period_start'], name='yr_ship_player_period_idx'), models.Index(fields=['player', 'ship_id', '-period_start'], name='yr_ship_player_shipprd_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'period_start', 'ship_id'), name='unique_player_yearly_ship_stats')],
            },
        ),
    ]
