# Generated by Django 5.2.12 on 2026-04-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0054_period_ship_stats_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_random_battle_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
