# Generated by Django 5.2.12 on 2026-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0056_battle_event_phase7_widening'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='battleevent',
            name='unique_battle_event_per_observation_pair',
        ),
        migrations.AddField(
            model_name='battleevent',
            name='mode',
            field=models.CharField(choices=[('random', 'Random'), ('ranked', 'Ranked')], db_index=True, default='random', max_length=8),
        ),
        migrations.AddField(
            model_name='battleevent',
            name='season_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='battleobservation',
            name='ranked_ships_stats_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='battleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'random')), fields=('from_observation', 'to_observation', 'ship_id'), name='unique_random_battle_event_per_observation_pair'),
        ),
        migrations.AddConstraint(
            model_name='battleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'ranked')), fields=('from_observation', 'to_observation', 'ship_id', 'season_id'), name='unique_ranked_battle_event_per_obs_pair_per_season'),
        ),
    ]
