# Generated by Django 5.2.12 on 2026-05-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0057_battle_event_mode_season_partitioning'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerdailyshipstats',
            name='unique_player_daily_ship_stats',
        ),
        migrations.AddField(
            model_name='playerdailyshipstats',
            name='mode',
            field=models.CharField(choices=[('random', 'Random'), ('ranked', 'Ranked')], db_index=True, default='random', max_length=8),
        ),
        migrations.AddField(
            model_name='playerdailyshipstats',
            name='season_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='playerdailyshipstats',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'random')), fields=('player', 'date', 'ship_id'), name='unique_random_player_daily_ship_stats'),
        ),
        migrations.AddConstraint(
            model_name='playerdailyshipstats',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'ranked')), fields=('player', 'date', 'ship_id', 'season_id'), name='unique_ranked_player_daily_ship_stats'),
        ),
    ]
