# Generated by Django 5.2.12 on 2026-05-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0058_daily_ship_stats_mode_partitioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingRecentPlayersSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4)),
                ('payload_json', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('realm',), name='unique_landing_recent_players_snapshot_per_realm')],
            },
        ),
    ]
