# Generated by Django 5.2.12 on 2026-06-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0059_landingrecentplayerssnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipTopPlayerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_on', models.DateField(db_index=True)),
                ('realm', models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], default='na', max_length=4)),
                ('ship_id', models.BigIntegerField(db_index=True)),
                ('ship_name', models.CharField(blank=True, default='', max_length=200)),
                ('rank', models.IntegerField()),
                ('win_rate', models.FloatField(default=0.0)),
                ('battles', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_top_player_badges', to='warships.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', '-captured_on'], name='ship_badge_player_captured_idx')],
                'constraints': [models.UniqueConstraint(fields=('captured_on', 'realm', 'ship_id', 'rank'), name='unique_ship_top_player_per_rank')],
            },
        ),
    ]
