# Generated by Django 5.2.12 on 2026-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0060_shiptopplayersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiptopplayersnapshot',
            name='damage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiptopplayersnapshot',
            name='frags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiptopplayersnapshot',
            name='survived',
            field=models.IntegerField(default=0),
        ),
    ]
