# Generated by Django 5.2.12 on 2026-06-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0063_battle_event_detected_brin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleobservation',
            name='source',
            field=models.CharField(choices=[('poll', 'Poll'), ('manual', 'Manual'), ('bulk_floor', 'Bulk Floor')], default='poll', max_length=12),
        ),
    ]
