# Generated by Django 5.1.15 on 2026-06-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warships", "0065_player_ranked_last_season_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerActivityHourly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        choices=[("na", "NA"), ("eu", "EU"), ("asia", "ASIA")],
                        default="na",
                        max_length=4,
                    ),
                ),
                ("hour", models.IntegerField()),
                ("player_count", models.IntegerField(default=0)),
                ("window_days", models.IntegerField(default=7)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["realm", "hour"], name="player_activity_realm_hour_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("realm", "hour"), name="player_activity_hourly_uniq"
                    )
                ],
            },
        ),
    ]
