# Generated by Django 5.2.12 on 2026-06-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0067_player_last_fetch_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingRecentPlayersSnapshot',
        ),
    ]
