# Generated by Django 5.2.12 on 2026-06-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0068_delete_landingrecentplayerssnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], db_index=True, default='na', max_length=4)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('last_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('active_days_window', models.IntegerField(default=0)),
                ('unique_sessions_window', models.IntegerField(default=0)),
                ('views_deduped_window', models.IntegerField(default=0)),
                ('hot_score', models.FloatField(db_index=True, default=0.0)),
                ('source', models.CharField(choices=[('engagement', 'Engagement'), ('pinned', 'Pinned')], default='engagement', max_length=16)),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_snapshotted_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_player_entries', to='warships.player')),
            ],
            options={
                'indexes': [models.Index(fields=['realm', '-hot_score'], name='hot_player_realm_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'realm'), name='unique_hot_player_realm')],
            },
        ),
    ]
