# Generated by Django 5.2.12 on 2026-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0069_hotplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enrichment_skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
