# Generated by Django 5.2.12 on 2026-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0070_player_enrichment_skipped_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipAward',
        ),
    ]
