# Generated by Django 5.2.12 on 2026-06-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0073_autovacuum_tuning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerweeklyshipstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playeryearlyshipstats',
            name='player',
        ),
        migrations.DeleteModel(
            name='PlayerMonthlyShipStats',
        ),
        migrations.DeleteModel(
            name='PlayerWeeklyShipStats',
        ),
        migrations.DeleteModel(
            name='PlayerYearlyShipStats',
        ),
    ]
