# Generated by Django 5.2.12 on 2026-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0077_ship_shiptool_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_idle_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
