# Generated by Django 5.2.12 on 2026-07-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0078_player_last_idle_check_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPlayerBestSnapshot',
        ),
    ]
