# Generated by Django 5.2.12 on 2026-07-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0079_delete_landingplayerbestsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedSeason',
            fields=[
                ('season_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
