# Generated by Django 5.2.12 on 2026-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0080_rankedseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanBattleSeason',
            fields=[
                ('season_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ship_tier_min', models.IntegerField(blank=True, null=True)),
                ('ship_tier_max', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='playerexplorersummary',
            name='clan_battle_current_season_battles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerexplorersummary',
            name='clan_battle_current_season_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerexplorersummary',
            name='clan_battle_current_season_win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
