# Generated by Django 5.2.12 on 2026-07-20 03:32
#
# DB table audit lever F7 (runbook-db-table-audit-2026-07-19.md): drop
# ~1 GB of never-scanned / prefix-covered indexes measured at idx_scan=0
# over the stats lifetime. The AlterFields drop single-column indexes that
# a composite/unique index prefix-covers; the RunSQL block drops Django's
# varchar_pattern_ops "_like" twins where the base btree stays (the twins
# only serve prefix-LIKE on non-C collations — search uses pg_trgm + ILIKE)
# and 4 never-scanned indexes on the mv_player_distribution_stats matview
# (unmanaged model, so RunSQL is the only channel). Names are the live
# Postgres names; IF EXISTS keeps this idempotent and harmless on fresh
# schemas that never had them. Reverse is a no-op by design — recreating
# dead indexes has no value.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0081_clanbattleseason_current_season'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playeractivityhourly',
            name='player_activity_realm_hour_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerdailyshipstats',
            name='dly_ship_date_battles_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerexplorersummary',
            name='explorer_realm_score_idx',
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='from_observation',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_events', to='warships.battleobservation'),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='season_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='to_observation',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_events', to='warships.battleobservation'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='playerexplorersummary',
            name='realm',
            field=models.CharField(choices=[('na', 'NA'), ('eu', 'EU'), ('asia', 'ASIA')], default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='player',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='warships.player'),
        ),
        migrations.AlterField(
            model_name='streamersubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        # varchar_pattern_ops twins whose base btree survives, plus the four
        # never-scanned matview indexes (REFRESH ... CONCURRENTLY only needs
        # the unique mv_player_dist_id_idx, which stays).
        migrations.RunSQL(
            sql=[
                'DROP INDEX IF EXISTS warships_player_enrichment_status_d3e4e33b_like;',
                'DROP INDEX IF EXISTS warships_playerdailyshipstats_mode_5a941e36_like;',
                'DROP INDEX IF EXISTS warships_battleevent_mode_983942c4_like;',
                'DROP INDEX IF EXISTS mv_player_dist_ratio_idx;',
                'DROP INDEX IF EXISTS mv_player_dist_survival_idx;',
                'DROP INDEX IF EXISTS mv_player_dist_realm_ratio_idx;',
                'DROP INDEX IF EXISTS mv_player_dist_realm_survival_idx;',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
