# Generated by Django 5.2.12 on 2026-07-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0082_drop_dead_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='battle_type',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='last_fetch',
        ),
    ]
