#!/usr/bin/env bash

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "Source this script instead of executing it:" >&2
  echo "  source ./scripts/use_local_hindsight_env.sh" >&2
  exit 1
fi

export ENABLE_AGENTIC_RUNTIME="${ENABLE_AGENTIC_RUNTIME:-1}"
export BATTLESTATS_HINDSIGHT_ENABLED="${BATTLESTATS_HINDSIGHT_ENABLED:-1}"
export BATTLESTATS_HINDSIGHT_API_URL="${BATTLESTATS_HINDSIGHT_API_URL:-http://127.0.0.1:8899}"
export BATTLESTATS_HINDSIGHT_BUDGET="${BATTLESTATS_HINDSIGHT_BUDGET:-mid}"
export BATTLESTATS_HINDSIGHT_MAX_TOKENS="${BATTLESTATS_HINDSIGHT_MAX_TOKENS:-4096}"
export BATTLESTATS_HINDSIGHT_TAGS="${BATTLESTATS_HINDSIGHT_TAGS:-project:battlestats,env:local,engine:langgraph}"

echo "Local Hindsight env enabled for this shell."
echo "ENABLE_AGENTIC_RUNTIME=${ENABLE_AGENTIC_RUNTIME}"
echo "BATTLESTATS_HINDSIGHT_ENABLED=${BATTLESTATS_HINDSIGHT_ENABLED}"
echo "BATTLESTATS_HINDSIGHT_API_URL=${BATTLESTATS_HINDSIGHT_API_URL}"
echo "BATTLESTATS_HINDSIGHT_BUDGET=${BATTLESTATS_HINDSIGHT_BUDGET}"
echo "BATTLESTATS_HINDSIGHT_MAX_TOKENS=${BATTLESTATS_HINDSIGHT_MAX_TOKENS}"
echo "BATTLESTATS_HINDSIGHT_TAGS=${BATTLESTATS_HINDSIGHT_TAGS}"